kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: cities-hpa
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: cities-deployment-latest
  targetCPUUtilizationPercentage: 50
