kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: citiesapi-hpa
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: citiesapi-deployment
  targetCPUUtilizationPercentage: 200
