apiVersion: v1
kind: PersistentVolume
metadata:
  name: org-assets-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: assets-share
    readOnly: false
