apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: org-assets-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
  volumeName: org-assets-pv
