apiVersion: v1
kind: PersistentVolume
metadata:
  name: orgapi-app-resources-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: app-resources
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orgapi-app-resources-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
  volumeName: orgapi-app-resources-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orgapi-shared-resources-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: shared-resources
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orgapi-shared-resources-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
  volumeName: orgapi-shared-resources-pv